### ISSUE TITLE
Add standard language about our data vs. learner data

### ISSUE THREAD

**Issue by mkamenet3** [UW-Madison-DataScience/geospatial-capstone#15]
Add standard language at the top of each capstone about what variables/rasters/vectors the capstone will be using vs. if learners are using their own data, to identify x,y,z.

**Comment by mkamenet3** [comment]
**Draft** example for raster capstone, 03-day2.Rmd:

In this capstone, we will be 3 Wisconsin rasters of 1) precipitation, 2) maximum temperature, 3) minimum temperature. We will be using the precipitation raster to review plotting rasters using `ggplot()` and maximum and minimum temperature rasters to perform raster math on. If you are using your own data, please identify at least 2 different rasters that you can use to perform raster math on - you can use the same raster to perform the raster plotting in part (1). The learning objectives of this capstone are to review importing plotting rasters with the `ggplot2` package and developing initial geospatial insights, to use the `overlay()` function to calculate summary statistics of your two rasters, and to reinforce writing functions in the `overlay()` function. 

All feedback welcome @sstevens2 @sjgraves @cidfreitag @claremichaud @srappel

**Comment by mkamenet3** [comment]
Things to standardize:

- [ ] Numbering in the capstone?
- [ ] Outline inside capstone or outside?
- [ ] Discussion section at the end?
- [ ] *spatial question* or *research question* or *spatial research question*
- [ ] *learner*
- [ ] package names are `packagename`, functions get parentheses `function()` ?
- [ ] resources or helpful links/further readings? At the end?
- [ ] our data vs. learner data standard language. What are we calling it?

**Comment by sjgraves** [comment]
Other things to standardize:

- [ ] code to do stuff on capstone data formatted as "challenge/solution" boxes?
- [ ] standard language for loading libraries
- [ ] if "questions" and "objectives" section are specific to capstone data or generic for whatever data
- [ ] when to load packages - right at the beginning or after some introduction to the day

**Comment by sstevens2** [comment]
Have learners create an Rmd file in the `reports/` directory of their project to work in.
